// 全局枚举
// 瓦片枚举

export enum TILE_TYPE_ENUM{
  WALL_ROW = 'WALL_ROW',
  WALL_COLUMN = 'WALL_COLUMN',
  WALL_LEFT_TOP = 'WALL_LEFT_TOP',
  WALL_RIGHT_TOP = 'WALL_RIGHT_TOP',
  WALL_LEFT_BOTTOM = 'WALL_LEFT_BOTTOM',
  WALL_RIGHT_BOTTOM = 'WALL_RIGHT_BOTTOM',
  CLIFF_LEFT = 'CLIFF_ROW_START',
  CLIFF_CENTER = 'CLIFF_ROW_CENTER',
  CLIFF_RIGHT = 'CLIFF_ROW_END',
  FLOOR = 'FLOOR',
}
export enum SCEEN_ENUM{
  loading="Loading",
  start="start",
  battle="battle",
}
export enum MENU_ENUM{
  NEXT_LEVEL="NEXT_LEVEL",
  LAST_LEVEL="LAST_LEVEL",
  UNDO="UNDO",
  OUT="OUT",
  RESTART="RESTART",
}
export enum EVENT_ENUM{
  NEXT_LEVEL="NEXT_LEVEL",
  PLAYER_CTRL="PLAYER_CTRL",
  PLAYER_MOVE_END="PLAYER_MOVE_END",
  PLAYER_DEATH="PLAYER_DEATH",
  PLAYER_AIRDEATH="PLAYER_AIRDEATH",
  ENEMY_DEATH="ENEMY_DEATH",
  CHECKDOOR="CHECKDOOR",
  GEN_SMOKE="GEN_SMOKE",
  SCREEN_SHAKE="SCREEN_SHAKE",
  RECORD="RECORD",
  UNDO="UNDO",
}
export enum CONTROLLER_ENUM{
  TOP="TOP",
  BOTTOM="BOTTOM",
  LEFT="LEFT",
  RIGHT="RIGHT",
  TURNLEFT="TURNLEFT",
  TURNRIGHT="TURNRIGHT",
}
export enum PARAMS_NAME_ENUM{
  IDLE = 'IDLE',
  ATTACK = 'ATTACK',
  TURNLEFT = 'TURNLEFT',
  TURNRIGHT = 'TURNRIGHT',
  // BLOCK="BLOCK",
  BLOCKFRONT = 'BLOCKFRONT',
  BLOCKBACK = 'BLOCKBACK',
  BLOCKLEFT = 'BLOCKLEFT',
  BLOCKRIGHT = 'BLOCKRIGHT',
  BLOCKTURNLEFT = 'BLOCKTURNLEFT',
  BLOCKTURNRIGHT = 'BLOCKTURNRIGHT',
  DEATH = 'DEATH',
  AIRDEATH = 'AIRDEATH',
  DIRECTION = 'DIRECTION',
  SPIKES_TOTAL_COUNT = 'SPIKES_TOTAL_COUNT',
  SPIKES_CUR_COUNT = 'SPIKES_CUR_COUNT',

}

export enum FSM_PARAMS_TYPE_ENUM{
  TRIGGER,
  NUMBER,
}
export enum DIRECTION_ORDER_ENUM{
  TOP=1,
  RIGHT=2,
  BOTTOM=3,
  LEFT=4,
}
export enum DIRECTION_ENUM{
  TOP="TOP",
  RIGHT="RIGHT",
  BOTTOM="BOTTOM",
  LEFT="LEFT",
}
export enum ENTITY_STATE_ENUM{
  IDLE = 'IDLE',
  ATTACK = 'ATTACK',
  TURNLEFT = 'TURNLEFT',
  TURNRIGHT = 'TURNRIGHT',
  BLOCKFRONT = 'BLOCKFRONT',
  BLOCKBACK = 'BLOCKBACK',
  BLOCKLEFT = 'BLOCKLEFT',
  BLOCKRIGHT = 'BLOCKRIGHT',
  BLOCKTURNLEFT = 'BLOCKTURNLEFT',
  BLOCKTURNRIGHT = 'BLOCKTURNRIGHT',
  DEATH = 'DEATH',
  AIRDEATH = 'AIRDEATH',
  SPIKES_ONE='PIKES_ONE',
  SPIKES_TWO='SPIKES_TWO',
  SPIKES_THREE='SPIKES_THREE',
  SPIKES_FOUR='SPIKES_FOUR',

}
export enum DOOR_STATE_ENUM{
  CLOSE="CLOSE",
  OPEN="OPEN",
}
export enum SPIKE_STATE_ENUM{
  SPIKES_ONE=2,
  SPIKES_TWO=3,
  SPIKES_THREE=4,
  SPIKES_FOUR=5,
}
export enum SPIKE_CUR_ENUM{
  SPIKES_ONE='PIKES_ONE',
  SPIKES_TWO='SPIKES_TWO',
  SPIKES_THREE='SPIKES_THREE',
  SPIKES_FOUR='SPIKES_FOUR',
  SPIKES_FIVE='SPIKES_FIVE',
}
export enum ENTITY_TYPE_ENUM{
  PLAYER,
  SKELETON_WOODEN,
  SKELETON_IRON,
  ENEMY,
  DOOR,
  SPIKES_ONE,
  SPIKES_TWO,
  SPIKES_THREE,
  SPIKES_FOUR,
  BURST,
  SMOKE,
}
